CREATE DATABASE DB_InLock;
GO

USE DB_InLock;
GO

CREATE TABLE TBL_Estudio(
IdEstudio INT PRIMARY KEY IDENTITY (1,1),
NomeEstudio VARCHAR(200) NOT NULL
);

CREATE TABLE TBL_Jogo(
IdJogo INT PRIMARY KEY IDENTITY (1,1),
NomeJogo VARCHAR(200) NOT NULL,
Descricao VARCHAR(500) NOT NULL,
DataLancamento DATE NOT NULL,
Valor REAL NOT NULL,
FK_IdEstudio INT FOREIGN KEY REFERENCES TBL_Estudio(IdEstudio) NOT NULL
);

CREATE TABLE TBL_TipoUsuario(
IdTipoUsuario INT PRIMARY KEY IDENTITY (1,1),
TituloTipoUsuario VARCHAR(200) NOT NULL
);

CREATE TABLE TBL_Usuario(
IdUsuario INT PRIMARY KEY IDENTITY (1,1),
Email VARCHAR(200) NOT NULL,
Senha VARCHAR(20) NOT NULL,
FK_IdTipoUsuario INT FOREIGN KEY REFERENCES TBL_TipoUsuario(IdTipoUsuario)
);
